cours_message:
    resource: "@CoursBundle/Controller/MessageController.php"
    type:     annotation

cours_user:
    resource: "@CoursBundle/Controller/UserController.php"
    type:     annotation

cours_cours:
    resource: "@CoursBundle/Controller/CoursController.php"
    type:     annotation

cours_cours:
    resource: "@CoursBundle/Controller/CoursController.php"
    type:     annotation

cours:
    resource: "@CoursBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
